services:
  - type: web
    name: laravel-reading-ai
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: AISpeech
          property: host
      - key: DB_PORT
        fromDatabase:
          name: AISpeech
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: AISpeech
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: AISpeech
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: AISpeech
          property: password

databases:
  - name: AISpeech
